"""Initial schema

Revision ID: 6b23780b6431
Revises: 
Create Date: 2026-08-30 22:52:30.814252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b23780b6431'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('centres',
    sa.Column('centre_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('centre_id')
    )
    op.create_index(op.f('ix_centres_centre_id'), 'centres', ['centre_id'], unique=False)
    op.create_table('operational_events',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('metadata_payload', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_operational_events_event_id'), 'operational_events', ['event_id'], unique=False)
    op.create_index(op.f('ix_operational_events_timestamp'), 'operational_events', ['timestamp'], unique=False)
    op.create_table('bookings',
    sa.Column('booking_id', sa.String(), nullable=False),
    sa.Column('farmer_id', sa.String(), nullable=True),
    sa.Column('centre_id', sa.String(), nullable=True),
    sa.Column('scheduled_start_time', sa.DateTime(), nullable=True),
    sa.Column('scheduled_end_time', sa.DateTime(), nullable=True),
    sa.Column('booking_state', sa.Enum('SCHEDULED', 'RESCHEDULED', 'ARRIVED', 'PROCESSING', 'COMPLETED', 'CANCELLED', 'NO_SHOW', name='bookingstate'), nullable=True),
    sa.Column('procurement_status', sa.Enum('NOT_STARTED', 'QUALITY_CHECK', 'WEIGHING', 'COMPLETED', name='procurementstatus'), nullable=True),
    sa.Column('payment_status', sa.Enum('NOT_INITIATED', 'PROCESSING', 'COMPLETED', 'FAILED', 'ACTION_REQUIRED', name='paymentstatus'), nullable=True),
    sa.Column('priority_level', sa.Integer(), nullable=True),
    sa.Column('reschedule_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['centre_id'], ['centres.centre_id'], ),
    sa.PrimaryKeyConstraint('booking_id')
    )
    op.create_index(op.f('ix_bookings_booking_id'), 'bookings', ['booking_id'], unique=False)
    op.create_index(op.f('ix_bookings_centre_id'), 'bookings', ['centre_id'], unique=False)
    op.create_index(op.f('ix_bookings_farmer_id'), 'bookings', ['farmer_id'], unique=False)
    op.create_table('centre_state_snapshots',
    sa.Column('snapshot_id', sa.String(), nullable=False),
    sa.Column('centre_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('state_payload', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['centre_id'], ['centres.centre_id'], ),
    sa.PrimaryKeyConstraint('snapshot_id')
    )
    op.create_index(op.f('ix_centre_state_snapshots_centre_id'), 'centre_state_snapshots', ['centre_id'], unique=False)
    op.create_index(op.f('ix_centre_state_snapshots_snapshot_id'), 'centre_state_snapshots', ['snapshot_id'], unique=False)
    op.create_index(op.f('ix_centre_state_snapshots_timestamp'), 'centre_state_snapshots', ['timestamp'], unique=False)
    op.create_table('constraint_sets',
    sa.Column('centre_id', sa.String(), nullable=False),
    sa.Column('operating_hours_start', sa.String(), nullable=True),
    sa.Column('operating_hours_end', sa.String(), nullable=True),
    sa.Column('slot_capacity', sa.Integer(), nullable=True),
    sa.Column('booking_validity_window_minutes', sa.Integer(), nullable=True),
    sa.Column('available_capacity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['centre_id'], ['centres.centre_id'], ),
    sa.PrimaryKeyConstraint('centre_id')
    )
    op.create_table('counters',
    sa.Column('counter_id', sa.String(), nullable=False),
    sa.Column('centre_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'UNAVAILABLE', name='counterstatus'), nullable=True),
    sa.Column('processing_rate', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['centre_id'], ['centres.centre_id'], ),
    sa.PrimaryKeyConstraint('counter_id')
    )
    op.create_index(op.f('ix_counters_counter_id'), 'counters', ['counter_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('recommendation_id', sa.String(), nullable=False),
    sa.Column('centre_id', sa.String(), nullable=True),
    sa.Column('trigger_event_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('expected_impact', sa.String(), nullable=True),
    sa.Column('constraint_check', sa.String(), nullable=True),
    sa.Column('fairness_check', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['centre_id'], ['centres.centre_id'], ),
    sa.PrimaryKeyConstraint('recommendation_id')
    )
    op.create_index(op.f('ix_recommendations_centre_id'), 'recommendations', ['centre_id'], unique=False)
    op.create_index(op.f('ix_recommendations_recommendation_id'), 'recommendations', ['recommendation_id'], unique=False)
    op.create_table('recommendation_changes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recommendation_id', sa.String(), nullable=True),
    sa.Column('booking_id', sa.String(), nullable=True),
    sa.Column('original_start', sa.DateTime(), nullable=True),
    sa.Column('proposed_start', sa.DateTime(), nullable=True),
    sa.Column('priority_level', sa.Integer(), nullable=True),
    sa.Column('reschedule_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.recommendation_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recommendation_changes')
    op.drop_index(op.f('ix_recommendations_recommendation_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_centre_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_counters_counter_id'), table_name='counters')
    op.drop_table('counters')
    op.drop_table('constraint_sets')
    op.drop_index(op.f('ix_centre_state_snapshots_timestamp'), table_name='centre_state_snapshots')
    op.drop_index(op.f('ix_centre_state_snapshots_snapshot_id'), table_name='centre_state_snapshots')
    op.drop_index(op.f('ix_centre_state_snapshots_centre_id'), table_name='centre_state_snapshots')
    op.drop_table('centre_state_snapshots')
    op.drop_index(op.f('ix_bookings_farmer_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_centre_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_booking_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_operational_events_timestamp'), table_name='operational_events')
    op.drop_index(op.f('ix_operational_events_event_id'), table_name='operational_events')
    op.drop_table('operational_events')
    op.drop_index(op.f('ix_centres_centre_id'), table_name='centres')
    op.drop_table('centres')
    # ### end Alembic commands ###
